### ISSUE TITLE
Server returns error

### ISSUE THREAD

**Issue by MikhailRokhin** [bo32/gnome-shell-extension-currency-converter#1]
![screenshot from 2015-12-21 17-55-26](https://cloud.githubusercontent.com/assets/16386541/11934429/53fc0490-a813-11e5-9db8-5d47c192d47f.png)

**Comment by bo32** [comment]
Hi. Did you create a free  account on currencylayer? Did you then enter your own key in the parameters of the extension?

**Comment by MikhailRokhin** [comment]
No. Could you add the info about necessity of registration and obtaining API key in the description of https://extensions.gnome.org/extension/984/currency-converter/   ?

**Comment by bo32** [comment]
Good idea, I will (even though the instructions are in the README file, and consequently in the github project main page, the one you have open on your screenshot ;) )

**Comment by MikhailRokhin** [comment]
No. Could you add the info about necessity of registration and obtaining API key in the description of https://extensions.gnome.org/extension/984/currency-converter/   ?

**Comment by MikhailRokhin** [comment]
Thank you.
